/* This file was generated by KAT at 00:53:03 on March 20 2002. */

#include <Mst.h>
#define MCDGEOM_R_SHOULDER		0
#define MCDGEOM_R_KNEE		1
#define MCDGEOM_R_HIP		2
#define MCDGEOM_R_ELBOW		3
#define MCDGEOM_PELVIS		4
#define MCDGEOM_NECK		5
#define MCDGEOM_MID_BACK		6
#define MCDGEOM_L_SHOULDER		7
#define MCDGEOM_L_KNEE		8
#define MCDGEOM_L_HIP		9
#define MCDGEOM_L_ELBOW		10
#define MCDMODEL_L_ELBOW		0
#define MCDMODEL_L_HIP		1
#define MCDMODEL_L_KNEE		2
#define MCDMODEL_L_SHOULDER		3
#define MCDMODEL_LOWER_BACK		4
#define MCDMODEL_MID_BACK		5
#define MCDMODEL_NECK		6
#define MCDMODEL_PELVIS		7
#define MCDMODEL_R_ELBOW		8
#define MCDMODEL_R_HIP		9
#define MCDMODEL_R_KNEE		10
#define MCDMODEL_R_SHOULDER		11
#define MDTCONSTRAINT_R_SHOULDER		0
#define MDTCONSTRAINT_R_KNEE		1
#define MDTCONSTRAINT_R_HIP		2
#define MDTCONSTRAINT_R_ELBOW		3
#define MDTCONSTRAINT_NECK		4
#define MDTCONSTRAINT_MID_BACK		5
#define MDTCONSTRAINT_LOWER_BACK		6
#define MDTCONSTRAINT_L_SHOULDER		7
#define MDTCONSTRAINT_L_KNEE		8
#define MDTCONSTRAINT_L_HIP		9
#define MDTCONSTRAINT_L_ELBOW		10

McdGeometryID agGeom[11] = {0};
McdModelID model[12] = {0};
MdtBodyID body[12] = {0};
MdtConstraintID constraint[11] = {0};
MdtBSJointID bs[11] = {0};
MdtHingeID hinge[11] = {0};
MdtPrismaticID prismatic[11] = {0};
MdtCarWheelID carwheel[11] = {0};
MdtSkeletalID skeletal[11] = {0};
MdtRPROJointID rpro[11] = {0};
MdtUniversalID universal[11] = {0};
MdtConeLimitID conelimit[11] = {0};
McdGeometryID nullGeom;

void MEAPI CreateAsset(McdFrameworkID fwk, McdSpaceID space, MdtWorldID world)
{

	nullGeom = McdNullCreate(fwk);

	/* r_shoulder McdGeometry */
	agGeom[MCDGEOM_R_SHOULDER] = McdAggregateCreate(fwk, 1);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.160000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = -0.100000f; tmPtr[3][1] = 0.000000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_R_SHOULDER], elemGeom, tmPtr);
		}
	}

	/* r_knee McdGeometry */
	agGeom[MCDGEOM_R_KNEE] = McdAggregateCreate(fwk, 2);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.180000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.000000f; tmPtr[3][1] = 0.100000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_R_KNEE], elemGeom, tmPtr);
		}
	}

	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.200000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.000000f; tmPtr[3][1] = 0.800000f; tmPtr[3][2] = -0.100000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_R_KNEE], elemGeom, tmPtr);
		}
	}

	/* r_hip McdGeometry */
	agGeom[MCDGEOM_R_HIP] = McdAggregateCreate(fwk, 1);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.240000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = -0.050000f; tmPtr[3][1] = 0.350000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_R_HIP], elemGeom, tmPtr);
		}
	}

	/* r_elbow McdGeometry */
	agGeom[MCDGEOM_R_ELBOW] = McdAggregateCreate(fwk, 2);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.180000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = -0.100000f; tmPtr[3][1] = 0.000000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_R_ELBOW], elemGeom, tmPtr);
		}
	}

	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.100000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = -0.550000f; tmPtr[3][1] = 0.000000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_R_ELBOW], elemGeom, tmPtr);
		}
	}

	/* pelvis McdGeometry */
	agGeom[MCDGEOM_PELVIS] = McdAggregateCreate(fwk, 1);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.250000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.000000f; tmPtr[3][1] = 0.000000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_PELVIS], elemGeom, tmPtr);
		}
	}

	/* neck McdGeometry */
	agGeom[MCDGEOM_NECK] = McdAggregateCreate(fwk, 1);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.200000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.000000f; tmPtr[3][1] = -0.300000f; tmPtr[3][2] = 0.100000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_NECK], elemGeom, tmPtr);
		}
	}

	/* mid_back McdGeometry */
	agGeom[MCDGEOM_MID_BACK] = McdAggregateCreate(fwk, 1);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.250000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.000000f; tmPtr[3][1] = -0.200000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_MID_BACK], elemGeom, tmPtr);
		}
	}

	/* l_shoulder McdGeometry */
	agGeom[MCDGEOM_L_SHOULDER] = McdAggregateCreate(fwk, 1);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.160000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.100000f; tmPtr[3][1] = 0.000000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_L_SHOULDER], elemGeom, tmPtr);
		}
	}

	/* l_knee McdGeometry */
	agGeom[MCDGEOM_L_KNEE] = McdAggregateCreate(fwk, 2);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.180000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.000000f; tmPtr[3][1] = 0.100000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_L_KNEE], elemGeom, tmPtr);
		}
	}

	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.200000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.000000f; tmPtr[3][1] = 0.800000f; tmPtr[3][2] = -0.100000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_L_KNEE], elemGeom, tmPtr);
		}
	}

	/* l_hip McdGeometry */
	agGeom[MCDGEOM_L_HIP] = McdAggregateCreate(fwk, 1);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.240000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.050000f; tmPtr[3][1] = 0.350000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_L_HIP], elemGeom, tmPtr);
		}
	}

	/* l_elbow McdGeometry */
	agGeom[MCDGEOM_L_ELBOW] = McdAggregateCreate(fwk, 2);
	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.180000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.100000f; tmPtr[3][1] = 0.000000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_L_ELBOW], elemGeom, tmPtr);
		}
	}

	{
		McdGeometryID elemGeom;
		elemGeom = McdSphereCreate(fwk, 0.100000f);
		{
			MeMatrix4Ptr tmPtr = (MeMatrix4Ptr)MeMemoryAPI.createAligned(sizeof(MeMatrix4), 16);
			tmPtr[0][0] = 1.000000f; tmPtr[0][1] = 0.000000f; tmPtr[0][2] = 0.000000f; tmPtr[0][3] = 0.000000f;
			tmPtr[1][0] = 0.000000f; tmPtr[1][1] = 1.000000f; tmPtr[1][2] = 0.000000f; tmPtr[1][3] = 0.000000f;
			tmPtr[2][0] = 0.000000f; tmPtr[2][1] = 0.000000f; tmPtr[2][2] = 1.000000f; tmPtr[2][3] = 0.000000f;
			tmPtr[3][0] = 0.550000f; tmPtr[3][1] = 0.000000f; tmPtr[3][2] = 0.000000f; tmPtr[3][3] = 1.000000f;
			McdAggregateAddElement(agGeom[MCDGEOM_L_ELBOW], elemGeom, tmPtr);
		}
	}

	/* l_elbow McdModel/MdtBody */
	model[MCDMODEL_L_ELBOW] = McdModelCreate(agGeom[MCDGEOM_L_ELBOW]);
	McdSpaceInsertModel(space, model[MCDMODEL_L_ELBOW]);
	body[MCDMODEL_L_ELBOW] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_L_ELBOW], 0.028618f);
	{
		MeVector3 offset;
		MeVector3Set(offset, 0.200000f, -0.000000f, 0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_L_ELBOW], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.016960f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.042262f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.042262f;
		MdtBodySetInertiaTensor(body[MCDMODEL_L_ELBOW], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_L_ELBOW], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_L_ELBOW], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = 0.000000f; tm[0][2] = 0.000002f; tm[0][3] = 0.000000f;
		tm[1][0] = -0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000004f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000002f; tm[2][1] = -0.000004f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = -0.891036f; tm[3][1] = 2.729999f; tm[3][2] = -0.095186f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_L_ELBOW], tm);
	}
	McdModelSetBody(model[MCDMODEL_L_ELBOW], body[MCDMODEL_L_ELBOW]);

	/* l_hip McdModel/MdtBody */
	model[MCDMODEL_L_HIP] = McdModelCreate(agGeom[MCDGEOM_L_HIP]);
	McdSpaceInsertModel(space, model[MCDMODEL_L_HIP]);
	body[MCDMODEL_L_HIP] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_L_HIP], 0.057906f);
	{
		MeVector3 offset;
		MeVector3Set(offset, 0.100000f, 0.400000f, -0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_L_HIP], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.023040f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.023040f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.023040f;
		MdtBodySetInertiaTensor(body[MCDMODEL_L_HIP], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_L_HIP], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_L_HIP], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = -0.000000f; tm[0][2] = 0.000000f; tm[0][3] = 0.000000f;
		tm[1][0] = 0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000000f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000000f; tm[2][1] = -0.000000f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = -0.228336f; tm[3][1] = 1.806697f; tm[3][2] = 0.005593f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_L_HIP], tm);
	}
	McdModelSetBody(model[MCDMODEL_L_HIP], body[MCDMODEL_L_HIP]);

	/* l_knee McdModel/MdtBody */
	model[MCDMODEL_L_KNEE] = McdModelCreate(agGeom[MCDGEOM_L_KNEE]);
	McdSpaceInsertModel(space, model[MCDMODEL_L_KNEE]);
	body[MCDMODEL_L_KNEE] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_L_KNEE], 0.057939f);
	{
		MeVector3 offset;
		MeVector3Set(offset, -0.000000f, 0.400000f, -0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_L_KNEE], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.150889f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.031399f; I[1][2] = 0.017070f;
		I[2][0] = 0.000000f; I[2][1] = 0.017070f; I[2][2] = 0.148451f;
		MdtBodySetInertiaTensor(body[MCDMODEL_L_KNEE], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_L_KNEE], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_L_KNEE], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = 0.000000f; tm[0][2] = 0.000001f; tm[0][3] = 0.000000f;
		tm[1][0] = -0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000002f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000001f; tm[2][1] = -0.000002f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = -0.211909f; tm[3][1] = 1.048585f; tm[3][2] = -0.017257f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_L_KNEE], tm);
	}
	McdModelSetBody(model[MCDMODEL_L_KNEE], body[MCDMODEL_L_KNEE]);

	/* l_shoulder McdModel/MdtBody */
	model[MCDMODEL_L_SHOULDER] = McdModelCreate(agGeom[MCDGEOM_L_SHOULDER]);
	McdSpaceInsertModel(space, model[MCDMODEL_L_SHOULDER]);
	body[MCDMODEL_L_SHOULDER] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_L_SHOULDER], 0.017157f);
	{
		MeVector3 offset;
		MeVector3Set(offset, 0.100000f, -0.000000f, 0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_L_SHOULDER], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.010240f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.010240f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.010240f;
		MdtBodySetInertiaTensor(body[MCDMODEL_L_SHOULDER], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_L_SHOULDER], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_L_SHOULDER], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = -0.000000f; tm[0][2] = 0.000000f; tm[0][3] = 0.000000f;
		tm[1][0] = 0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000000f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000000f; tm[2][1] = -0.000000f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = -0.398225f; tm[3][1] = 2.734898f; tm[3][2] = -0.073559f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_L_SHOULDER], tm);
	}
	McdModelSetBody(model[MCDMODEL_L_SHOULDER], body[MCDMODEL_L_SHOULDER]);

	/* lower_back McdModel/MdtBody */
	model[MCDMODEL_LOWER_BACK] = McdModelCreate(nullGeom);
	body[MCDMODEL_LOWER_BACK] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_LOWER_BACK], 0.300000f);
	{
		MeVector3 offset;
		MeVector3Set(offset, 0.000000f, 0.000000f, 0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_LOWER_BACK], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.004800f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.004800f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.004800f;
		MdtBodySetInertiaTensor(body[MCDMODEL_LOWER_BACK], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_LOWER_BACK], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_LOWER_BACK], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = -0.000000f; tm[0][2] = 0.000000f; tm[0][3] = 0.000000f;
		tm[1][0] = 0.000000f; tm[1][1] = -1.000000f; tm[1][2] = 0.000000f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000000f; tm[2][1] = 0.000000f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = 0.000085f; tm[3][1] = 2.040688f; tm[3][2] = -0.030392f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_LOWER_BACK], tm);
	}
	McdModelSetBody(model[MCDMODEL_LOWER_BACK], body[MCDMODEL_LOWER_BACK]);

	/* mid_back McdModel/MdtBody */
	model[MCDMODEL_MID_BACK] = McdModelCreate(agGeom[MCDGEOM_MID_BACK]);
	McdSpaceInsertModel(space, model[MCDMODEL_MID_BACK]);
	body[MCDMODEL_MID_BACK] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_MID_BACK], 0.065450f);
	{
		MeVector3 offset;
		MeVector3Set(offset, -0.000000f, -0.200000f, 0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_MID_BACK], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.025000f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.025000f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.025000f;
		MdtBodySetInertiaTensor(body[MCDMODEL_MID_BACK], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_MID_BACK], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_MID_BACK], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = -0.000000f; tm[0][2] = 0.000000f; tm[0][3] = 0.000000f;
		tm[1][0] = 0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000000f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000000f; tm[2][1] = -0.000000f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = 0.001068f; tm[3][1] = 2.288244f; tm[3][2] = -0.030630f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_MID_BACK], tm);
	}
	McdModelSetBody(model[MCDMODEL_MID_BACK], body[MCDMODEL_MID_BACK]);

	/* neck McdModel/MdtBody */
	model[MCDMODEL_NECK] = McdModelCreate(agGeom[MCDGEOM_NECK]);
	McdSpaceInsertModel(space, model[MCDMODEL_NECK]);
	body[MCDMODEL_NECK] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_NECK], 0.033510f);
	{
		MeVector3 offset;
		MeVector3Set(offset, -0.000000f, -0.300000f, 0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_NECK], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.016000f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.016000f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.016000f;
		MdtBodySetInertiaTensor(body[MCDMODEL_NECK], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_NECK], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_NECK], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = -0.000000f; tm[0][2] = 0.000000f; tm[0][3] = 0.000000f;
		tm[1][0] = 0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000000f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000000f; tm[2][1] = -0.000000f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = 0.000166f; tm[3][1] = 2.806122f; tm[3][2] = -0.132592f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_NECK], tm);
	}
	McdModelSetBody(model[MCDMODEL_NECK], body[MCDMODEL_NECK]);

	/* pelvis McdModel/MdtBody */
	model[MCDMODEL_PELVIS] = McdModelCreate(agGeom[MCDGEOM_PELVIS]);
	McdSpaceInsertModel(space, model[MCDMODEL_PELVIS]);
	body[MCDMODEL_PELVIS] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_PELVIS], 0.065450f);
	{
		MeVector3 offset;
		MeVector3Set(offset, 0.000000f, 0.200000f, -0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_PELVIS], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.025000f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.025000f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.025000f;
		MdtBodySetInertiaTensor(body[MCDMODEL_PELVIS], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_PELVIS], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_PELVIS], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = -0.000000f; tm[0][2] = 0.000000f; tm[0][3] = 0.000000f;
		tm[1][0] = 0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000000f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000000f; tm[2][1] = -0.000000f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = 0.000170f; tm[3][1] = 1.881376f; tm[3][2] = 0.000000f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_PELVIS], tm);
	}
	McdModelSetBody(model[MCDMODEL_PELVIS], body[MCDMODEL_PELVIS]);

	/* r_elbow McdModel/MdtBody */
	model[MCDMODEL_R_ELBOW] = McdModelCreate(agGeom[MCDGEOM_R_ELBOW]);
	McdSpaceInsertModel(space, model[MCDMODEL_R_ELBOW]);
	body[MCDMODEL_R_ELBOW] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_R_ELBOW], 0.028618f);
	{
		MeVector3 offset;
		MeVector3Set(offset, -0.200000f, 0.000000f, -0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_R_ELBOW], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.016960f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.042262f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.042262f;
		MdtBodySetInertiaTensor(body[MCDMODEL_R_ELBOW], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_R_ELBOW], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_R_ELBOW], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = 0.000000f; tm[0][2] = 0.000002f; tm[0][3] = 0.000000f;
		tm[1][0] = -0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000004f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000002f; tm[2][1] = -0.000004f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = 0.878178f; tm[3][1] = 2.729760f; tm[3][2] = -0.093230f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_R_ELBOW], tm);
	}
	McdModelSetBody(model[MCDMODEL_R_ELBOW], body[MCDMODEL_R_ELBOW]);

	/* r_hip McdModel/MdtBody */
	model[MCDMODEL_R_HIP] = McdModelCreate(agGeom[MCDGEOM_R_HIP]);
	McdSpaceInsertModel(space, model[MCDMODEL_R_HIP]);
	body[MCDMODEL_R_HIP] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_R_HIP], 0.057906f);
	{
		MeVector3 offset;
		MeVector3Set(offset, -0.100000f, 0.400000f, -0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_R_HIP], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.023040f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.023040f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.023040f;
		MdtBodySetInertiaTensor(body[MCDMODEL_R_HIP], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_R_HIP], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_R_HIP], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = -0.000000f; tm[0][2] = 0.000000f; tm[0][3] = 0.000000f;
		tm[1][0] = 0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000000f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000000f; tm[2][1] = -0.000000f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = 0.231094f; tm[3][1] = 1.807489f; tm[3][2] = 0.006115f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_R_HIP], tm);
	}
	McdModelSetBody(model[MCDMODEL_R_HIP], body[MCDMODEL_R_HIP]);

	/* r_knee McdModel/MdtBody */
	model[MCDMODEL_R_KNEE] = McdModelCreate(agGeom[MCDGEOM_R_KNEE]);
	McdSpaceInsertModel(space, model[MCDMODEL_R_KNEE]);
	body[MCDMODEL_R_KNEE] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_R_KNEE], 0.057939f);
	{
		MeVector3 offset;
		MeVector3Set(offset, -0.000000f, 0.400000f, -0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_R_KNEE], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.150889f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.031399f; I[1][2] = 0.017070f;
		I[2][0] = 0.000000f; I[2][1] = 0.017070f; I[2][2] = 0.148451f;
		MdtBodySetInertiaTensor(body[MCDMODEL_R_KNEE], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_R_KNEE], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_R_KNEE], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = 0.000000f; tm[0][2] = 0.000001f; tm[0][3] = 0.000000f;
		tm[1][0] = -0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000002f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000001f; tm[2][1] = -0.000002f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = 0.218158f; tm[3][1] = 1.048631f; tm[3][2] = -0.017779f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_R_KNEE], tm);
	}
	McdModelSetBody(model[MCDMODEL_R_KNEE], body[MCDMODEL_R_KNEE]);

	/* r_shoulder McdModel/MdtBody */
	model[MCDMODEL_R_SHOULDER] = McdModelCreate(agGeom[MCDGEOM_R_SHOULDER]);
	McdSpaceInsertModel(space, model[MCDMODEL_R_SHOULDER]);
	body[MCDMODEL_R_SHOULDER] = MdtBodyCreate(world);
	MdtBodySetMass(body[MCDMODEL_R_SHOULDER], 0.017157f);
	{
		MeVector3 offset;
		MeVector3Set(offset, -0.100000f, 0.000000f, -0.000000f);
		MdtBodySetCenterOfMassRelativePosition(body[MCDMODEL_R_SHOULDER], offset);
	}
	{
		MeMatrix3 I;
		I[0][0] = 0.010240f; I[0][1] = 0.000000f; I[0][2] = 0.000000f;
		I[1][0] = 0.000000f; I[1][1] = 0.010240f; I[1][2] = 0.000000f;
		I[2][0] = 0.000000f; I[2][1] = 0.000000f; I[2][2] = 0.010240f;
		MdtBodySetInertiaTensor(body[MCDMODEL_R_SHOULDER], I);
	}
	MdtBodySetLinearVelocityDamping(body[MCDMODEL_R_SHOULDER], 0.000000f);
	MdtBodySetAngularVelocityDamping(body[MCDMODEL_R_SHOULDER], 0.000000f);
	{
		MeMatrix4 tm;
		tm[0][0] = -1.000000f; tm[0][1] = -0.000000f; tm[0][2] = 0.000000f; tm[0][3] = 0.000000f;
		tm[1][0] = 0.000000f; tm[1][1] = -1.000000f; tm[1][2] = -0.000000f; tm[1][3] = 0.000000f;
		tm[2][0] = 0.000000f; tm[2][1] = -0.000000f; tm[2][2] = 1.000000f; tm[2][3] = 0.000000f;
		tm[3][0] = 0.387783f; tm[3][1] = 2.735014f; tm[3][2] = -0.068559f; tm[3][3] = 1.000000f;
		MdtBodySetTransform(body[MCDMODEL_R_SHOULDER], tm);
	}
	McdModelSetBody(model[MCDMODEL_R_SHOULDER], body[MCDMODEL_R_SHOULDER]);

	McdSpaceDisablePair(model[MCDMODEL_L_ELBOW], model[MCDMODEL_L_SHOULDER]);
	McdSpaceDisablePair(model[MCDMODEL_L_HIP], model[MCDMODEL_L_KNEE]);
	McdSpaceDisablePair(model[MCDMODEL_L_HIP], model[MCDMODEL_PELVIS]);
	McdSpaceDisablePair(model[MCDMODEL_L_SHOULDER], model[MCDMODEL_MID_BACK]);
	McdSpaceDisablePair(model[MCDMODEL_MID_BACK], model[MCDMODEL_NECK]);
	McdSpaceDisablePair(model[MCDMODEL_MID_BACK], model[MCDMODEL_R_SHOULDER]);
	McdSpaceDisablePair(model[MCDMODEL_PELVIS], model[MCDMODEL_R_HIP]);
	McdSpaceDisablePair(model[MCDMODEL_R_ELBOW], model[MCDMODEL_R_SHOULDER]);
	McdSpaceDisablePair(model[MCDMODEL_R_HIP], model[MCDMODEL_R_KNEE]);

	/* r_shoulder MdtConstraint */
	hinge[MDTCONSTRAINT_R_SHOULDER] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_R_SHOULDER] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_R_SHOULDER]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_R_SHOULDER], body[MCDMODEL_R_SHOULDER], body[MCDMODEL_MID_BACK]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_R_SHOULDER], 0, -0.000000f, 0.000000f, 0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_R_SHOULDER], 0, 0.000000f, -0.000000f, 1.000000f, -0.008946f, -0.999960f, 0.000000f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_R_SHOULDER], 1, -0.386715f, -0.446770f, -0.037929f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_R_SHOULDER], 1, -0.000000f, 0.000000f, 1.000000f, -0.008946f, -0.999960f, 0.000000f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_R_SHOULDER]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_R_SHOULDER]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.800000f);
		MdtSingleLimitSetStop(lower, -0.800000f);
		MdtSingleLimitSetStiffness(upper, 500.000000f);
		MdtSingleLimitSetStiffness(lower, 500.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* r_knee MdtConstraint */
	hinge[MDTCONSTRAINT_R_KNEE] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_R_KNEE] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_R_KNEE]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_R_KNEE], body[MCDMODEL_R_KNEE], body[MCDMODEL_R_HIP]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_R_KNEE], 0, -0.000000f, -0.000000f, 0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_R_KNEE], 0, 1.000000f, -0.000000f, 0.000000f, 0.000000f, -0.998219f, 0.059657f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_R_KNEE], 1, 0.012935f, 0.758858f, -0.023893f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_R_KNEE], 1, 1.000000f, -0.000000f, 0.000001f, -0.000000f, -0.998219f, 0.059659f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_R_KNEE]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_R_KNEE]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.200000f);
		MdtSingleLimitSetStop(lower, -1.600000f);
		MdtSingleLimitSetStiffness(upper, 1000.000000f);
		MdtSingleLimitSetStiffness(lower, 1000.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* r_hip MdtConstraint */
	hinge[MDTCONSTRAINT_R_HIP] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_R_HIP] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_R_HIP]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_R_HIP], body[MCDMODEL_R_HIP], body[MCDMODEL_PELVIS]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_R_HIP], 0, 0.000000f, -0.000000f, 0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_R_HIP], 0, 1.000000f, -0.000000f, 0.000000f, 0.000000f, -0.998219f, 0.059657f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_R_HIP], 1, -0.230924f, 0.073887f, 0.006115f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_R_HIP], 1, 1.000000f, -0.000000f, 0.000000f, -0.000000f, -0.998219f, 0.059657f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_R_HIP]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_R_HIP]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.800000f);
		MdtSingleLimitSetStop(lower, -0.800000f);
		MdtSingleLimitSetStiffness(upper, 1000.000000f);
		MdtSingleLimitSetStiffness(lower, 1000.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* r_elbow MdtConstraint */
	hinge[MDTCONSTRAINT_R_ELBOW] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_R_ELBOW] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_R_ELBOW]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_R_ELBOW], body[MCDMODEL_R_ELBOW], body[MCDMODEL_R_SHOULDER]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_R_ELBOW], 0, 0.000000f, -0.000000f, 0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_R_ELBOW], 0, -0.000000f, 1.000000f, -0.000000f, -0.096413f, 0.000000f, 0.995341f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_R_ELBOW], 1, -0.490395f, 0.005254f, -0.024671f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_R_ELBOW], 1, 0.000000f, 1.000000f, -0.000004f, -0.096415f, 0.000004f, 0.995341f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_R_ELBOW]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_R_ELBOW]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.800000f);
		MdtSingleLimitSetStop(lower, -0.065428f);
		MdtSingleLimitSetStiffness(upper, 1000.000000f);
		MdtSingleLimitSetStiffness(lower, 1000.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* neck MdtConstraint */
	hinge[MDTCONSTRAINT_NECK] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_NECK] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_NECK]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_NECK], body[MCDMODEL_NECK], body[MCDMODEL_MID_BACK]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_NECK], 0, 0.000000f, 0.000000f, -0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_NECK], 0, 1.000000f, -0.000000f, 0.000000f, 0.000000f, -0.998219f, 0.059657f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_NECK], 1, 0.000902f, -0.517878f, -0.101962f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_NECK], 1, 1.000000f, -0.000000f, 0.000000f, -0.000000f, -0.998219f, 0.059657f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_NECK]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_NECK]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.400000f);
		MdtSingleLimitSetStop(lower, -0.400000f);
		MdtSingleLimitSetStiffness(upper, 500.000000f);
		MdtSingleLimitSetStiffness(lower, 500.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* mid_back MdtConstraint */
	hinge[MDTCONSTRAINT_MID_BACK] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_MID_BACK] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_MID_BACK]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_MID_BACK], body[MCDMODEL_MID_BACK], body[MCDMODEL_LOWER_BACK]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_MID_BACK], 0, -0.000000f, 0.000000f, -0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_MID_BACK], 0, 0.000000f, -0.000000f, 1.000000f, -0.008946f, -0.999960f, 0.000000f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_MID_BACK], 1, -0.000983f, -0.247556f, -0.000238f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_MID_BACK], 1, -0.000000f, 0.000000f, 1.000000f, -0.008946f, -0.999960f, 0.000000f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_MID_BACK]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_MID_BACK]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.800000f);
		MdtSingleLimitSetStop(lower, -0.800000f);
		MdtSingleLimitSetStiffness(upper, 500.000000f);
		MdtSingleLimitSetStiffness(lower, 500.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* lower_back MdtConstraint */
	hinge[MDTCONSTRAINT_LOWER_BACK] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_LOWER_BACK] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_LOWER_BACK]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_LOWER_BACK], body[MCDMODEL_LOWER_BACK], body[MCDMODEL_PELVIS]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_LOWER_BACK], 0, -0.000000f, 0.000000f, 0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_LOWER_BACK], 0, 1.000000f, -0.000000f, 0.000000f, 0.000000f, -0.998219f, 0.059657f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_LOWER_BACK], 1, 0.000085f, -0.159312f, -0.030391f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_LOWER_BACK], 1, 1.000000f, -0.000000f, -0.000000f, 0.000000f, -0.998219f, 0.059657f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_LOWER_BACK]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_LOWER_BACK]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.800000f);
		MdtSingleLimitSetStop(lower, -0.800000f);
		MdtSingleLimitSetStiffness(upper, 500.000000f);
		MdtSingleLimitSetStiffness(lower, 500.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* l_shoulder MdtConstraint */
	hinge[MDTCONSTRAINT_L_SHOULDER] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_L_SHOULDER] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_L_SHOULDER]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_L_SHOULDER], body[MCDMODEL_L_SHOULDER], body[MCDMODEL_MID_BACK]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_L_SHOULDER], 0, 0.000000f, -0.000000f, -0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_L_SHOULDER], 0, 0.000000f, -0.000000f, 1.000000f, -0.008946f, -0.999960f, 0.000000f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_L_SHOULDER], 1, 0.399293f, -0.446654f, -0.042929f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_L_SHOULDER], 1, -0.000000f, 0.000000f, 1.000000f, -0.008946f, -0.999960f, 0.000000f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_L_SHOULDER]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_L_SHOULDER]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.800000f);
		MdtSingleLimitSetStop(lower, -0.800000f);
		MdtSingleLimitSetStiffness(upper, 500.000000f);
		MdtSingleLimitSetStiffness(lower, 500.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* l_knee MdtConstraint */
	hinge[MDTCONSTRAINT_L_KNEE] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_L_KNEE] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_L_KNEE]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_L_KNEE], body[MCDMODEL_L_KNEE], body[MCDMODEL_L_HIP]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_L_KNEE], 0, -0.000000f, -0.000000f, -0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_L_KNEE], 0, 1.000000f, -0.000000f, 0.000000f, 0.000000f, -0.998219f, 0.059657f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_L_KNEE], 1, -0.016427f, 0.758112f, -0.022849f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_L_KNEE], 1, 1.000000f, -0.000000f, 0.000001f, -0.000000f, -0.998219f, 0.059659f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_L_KNEE]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_L_KNEE]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.200000f);
		MdtSingleLimitSetStop(lower, -1.600000f);
		MdtSingleLimitSetStiffness(upper, 1000.000000f);
		MdtSingleLimitSetStiffness(lower, 1000.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* l_hip MdtConstraint */
	hinge[MDTCONSTRAINT_L_HIP] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_L_HIP] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_L_HIP]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_L_HIP], body[MCDMODEL_L_HIP], body[MCDMODEL_PELVIS]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_L_HIP], 0, 0.000000f, -0.000000f, 0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_L_HIP], 0, 1.000000f, -0.000000f, 0.000000f, 0.000000f, -0.998219f, 0.059657f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_L_HIP], 1, 0.228505f, 0.074679f, 0.005593f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_L_HIP], 1, 1.000000f, -0.000000f, 0.000000f, -0.000000f, -0.998219f, 0.059657f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_L_HIP]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_L_HIP]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.800000f);
		MdtSingleLimitSetStop(lower, -0.800000f);
		MdtSingleLimitSetStiffness(upper, 1000.000000f);
		MdtSingleLimitSetStiffness(lower, 1000.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

	/* l_elbow MdtConstraint */
	hinge[MDTCONSTRAINT_L_ELBOW] = MdtHingeCreate(world);
	constraint[MDTCONSTRAINT_L_ELBOW] = MdtHingeQuaConstraint(hinge[MDTCONSTRAINT_L_ELBOW]);
	MdtConstraintSetBodies(constraint[MDTCONSTRAINT_L_ELBOW], body[MCDMODEL_L_ELBOW], body[MCDMODEL_L_SHOULDER]);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_L_ELBOW], 0, -0.000000f, -0.000000f, 0.000000f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_L_ELBOW], 0, -0.000000f, 1.000000f, -0.000000f, -0.096413f, 0.000000f, 0.995341f);
	MdtConstraintBodySetPositionRel(constraint[MDTCONSTRAINT_L_ELBOW], 1, 0.492811f, 0.004899f, -0.021627f);
	MdtConstraintBodySetAxesRel(constraint[MDTCONSTRAINT_L_ELBOW], 1, 0.000000f, 1.000000f, -0.000004f, -0.096415f, 0.000004f, 0.995341f);
	MdtConstraintEnable(constraint[MDTCONSTRAINT_L_ELBOW]);
	{
		MdtLimitID limit = MdtHingeGetLimit(hinge[MDTCONSTRAINT_L_ELBOW]);
		MdtSingleLimitID upper = MdtLimitGetUpperLimit(limit);
		MdtSingleLimitID lower = MdtLimitGetLowerLimit(limit);
		MdtSingleLimitSetStop(upper, 0.034223f);
		MdtSingleLimitSetStop(lower, -0.800000f);
		MdtSingleLimitSetStiffness(upper, 1000.000000f);
		MdtSingleLimitSetStiffness(lower, 1000.000000f);
		MdtLimitActivateLimits(limit, 1);
		/*MdtLimitSetLimitedForceMotor(limit, 1.000000f, 1000.000000f);*/
		/*MdtLimitActivateMotor(limit, 0);*/
	}

}

