<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title><%Title%></title>
	<meta http-equiv="Content-Type" content="text/html; charset=<%charset%>">
	<%RefreshMeta%>
	<link rel="stylesheet" type="text/css" href="<%CSS%>">
	<%JavaScripts%>
</head>
<body>

<table class="sectionheader">
<tr>
	<td>
	<center><b><%Section%></b></center>
	<center><%SubTitle%></center>
	<br />
	<%PageHelp%>
	<%Status%>
	</td>
</tr>
</table>

<br />
