/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef XGAME_API
#define XGAME_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern XGAME_API FName XGAME_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class XGAME_API AAimedAttachment : public AActor
{
public:
    FVector BaseOffset GCC_PACK(4);
    FVector AimedOffset;
    FLOAT DownwardBias;
    DECLARE_CLASS(AAimedAttachment,AActor,0,XGame)
    #include "AAimedAttachment.h"
};

struct XGAME_API FPlayerRecord
{
    FString DefaultName GCC_PACK(4);
    class UClass* Species;
    FString MeshName;
    FString BodySkinName;
    FString FaceSkinName;
    class UMaterial* Portrait;
    FString TextName;
    FString VoiceClassName;
    FString Sex;
    FString Accuracy;
    FString Aggressiveness;
    FString StrafingAbility;
    FString CombatStyle;
    FString Tactics;
    FString ReactionTime;
    FString Jumpiness;
    FString Race;
    FString FavoriteWeapon;
    FString Menu;
    FString Skeleton;
    INT RecordIndex;
    FString Ragdoll;
    BYTE BotUse;
    BITFIELD UseSpecular:1 GCC_PACK(4);
    BITFIELD TeamFace:1;
};


class XGAME_API UxUtil : public UObject
{
public:
    FStringNoInit SectionName GCC_PACK(4);
    FStringNoInit FileExtension;
    class UCachePlayers* CachedPlayerList;
    FStringNoInit NoPreference;
    FStringNoInit FavoriteWeapon;
    FStringNoInit AgilityString;
    FStringNoInit TacticsString;
    FStringNoInit AccuracyString;
    FStringNoInit AggressivenessString;
    DECLARE_FUNCTION(execLoadDecoText);
    DECLARE_FUNCTION(execFindUPLPlayerRecord);
    DECLARE_FUNCTION(execGetPlayerRecord);
    DECLARE_FUNCTION(execGetPlayerList);
    DECLARE_CLASS(UxUtil,UObject,0,XGame)
	static class UDecoText* LoadDecoText( const TCHAR* TextName, INT ColumnCount = DECO_TEXT_MAX_COLUMNS );
	void GetPlayerList();
};


class XGAME_API UCachePlayers : public UxUtil
{
public:
    TArrayNoInit<FPlayerRecord> Records GCC_PACK(4);
    DECLARE_CLASS(UCachePlayers,UxUtil,0,XGame)
    NO_DEFAULT_CONSTRUCTOR(UCachePlayers)
};


class XGAME_API UDecoText : public UObject
{
public:
    FStringNoInit TextName GCC_PACK(4);
    TArrayNoInit<FString> Rows;
    DECLARE_CLASS(UDecoText,UObject,0,XGame)
    NO_DEFAULT_CONSTRUCTOR(UDecoText)
};


class XGAME_API USpeciesType : public UObject
{
public:
    FStringNoInit MaleVoice GCC_PACK(4);
    FStringNoInit FemaleVoice;
    FStringNoInit GibGroup;
    FStringNoInit MaleRagSkelName;
    FStringNoInit FemaleRagSkelName;
    FStringNoInit FemaleSkeleton;
    FStringNoInit MaleSkeleton;
    FStringNoInit MaleSoundGroup;
    FStringNoInit FemaleSoundGroup;
    FStringNoInit PawnClassName;
    FStringNoInit SpeciesName;
    INT RaceNum;
    INT DMTeam;
    FName TauntAnims[16];
    FStringNoInit TauntAnimNames[16];
    FLOAT AirControl;
    FLOAT GroundSpeed;
    FLOAT WaterSpeed;
    FLOAT JumpZ;
    FLOAT ReceivedDamageScaling;
    FLOAT DamageScaling;
    FLOAT AccelRate;
    FLOAT WalkingPct;
    FLOAT CrouchedPct;
    FLOAT DodgeSpeedFactor;
    FLOAT DodgeSpeedZ;
    DECLARE_CLASS(USpeciesType,UObject,0,XGame)
    NO_DEFAULT_CONSTRUCTOR(USpeciesType)
};

#endif

AUTOGENERATE_FUNCTION(UxUtil,-1,execLoadDecoText);
AUTOGENERATE_FUNCTION(UxUtil,564,execFindUPLPlayerRecord);
AUTOGENERATE_FUNCTION(UxUtil,563,execGetPlayerRecord);
AUTOGENERATE_FUNCTION(UxUtil,562,execGetPlayerList);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif


#ifdef NATIVE_DEFS_ONLY
DECLARE_NATIVE_TYPE(XGame,AAimedAttachment);
DECLARE_NATIVE_TYPE(XGame,UCachePlayers);
DECLARE_NATIVE_TYPE(XGame,UxUtil);
DECLARE_NATIVE_TYPE(XGame,UDecoText);
DECLARE_NATIVE_TYPE(XGame,USpeciesType);

#define AUTO_INITIALIZE_REGISTRANTS_XGAME \
	AAimedAttachment::StaticClass(); \
	UCachePlayers::StaticClass(); \
	UxUtil::StaticClass(); \
	GNativeLookupFuncs[Lookup++] = &FindXGameUxUtilNative; \
	UDecoText::StaticClass(); \
	USpeciesType::StaticClass(); \

#endif // NATIVE_DEFS_ONLY

#ifdef NATIVES_ONLY
NATIVE_INFO(UxUtil) GXGameUxUtilNatives[] = 
{ 
	MAP_NATIVE(UxUtil,execLoadDecoText)
	MAP_NATIVE(UxUtil,execFindUPLPlayerRecord)
	MAP_NATIVE(UxUtil,execGetPlayerRecord)
	MAP_NATIVE(UxUtil,execGetPlayerList)
	{NULL,NULL}
};
IMPLEMENT_NATIVE_HANDLER(XGame,UxUtil);

#endif // NATIVES_ONLY

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(AAimedAttachment)
VERIFY_CLASS_SIZE_NODIE(UCachePlayers)
VERIFY_CLASS_SIZE_NODIE(UxUtil)
VERIFY_CLASS_SIZE_NODIE(UDecoText)
VERIFY_CLASS_SIZE_NODIE(USpeciesType)
#endif // VERIFY_CLASS_SIZES
